/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { AgentPermissionEdit } from './agentPermissionEdit'
import type { AgentPermissionBash } from './agentPermissionBash'
import type { AgentPermissionWebfetch } from './agentPermissionWebfetch'

export type AgentPermission = {
  edit: AgentPermissionEdit
  bash: AgentPermissionBash
  webfetch?: AgentPermissionWebfetch
}
