/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { AgentPartSource } from './agentPartSource'

export interface AgentPart {
  id: string
  sessionID: string
  messageID: string
  type: 'agent'
  name: string
  source?: AgentPartSource
}
