/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { AgentPartInputSource } from './agentPartInputSource'

export interface AgentPartInput {
  id?: string
  type: 'agent'
  name: string
  source?: AgentPartInputSource
}
