/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { AgentMode } from './agentMode'
import type { AgentPermission } from './agentPermission'
import type { AgentModel } from './agentModel'
import type { AgentTools } from './agentTools'
import type { AgentOptions } from './agentOptions'

export interface Agent {
  name: string
  description?: string
  mode: AgentMode
  builtIn: boolean
  topP?: number
  temperature?: number
  permission: AgentPermission
  model?: AgentModel
  prompt?: string
  tools: AgentTools
  options: AgentOptions
}
