/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { AgentConfigPermissionEdit } from './agentConfigPermissionEdit'
import type { AgentConfigPermissionBash } from './agentConfigPermissionBash'
import type { AgentConfigPermissionWebfetch } from './agentConfigPermissionWebfetch'

export type AgentConfigPermission = {
  edit?: AgentConfigPermissionEdit
  bash?: AgentConfigPermissionBash
  webfetch?: AgentConfigPermissionWebfetch
}
