/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { AgentConfigTools } from './agentConfigTools'
import type { AgentConfigMode } from './agentConfigMode'
import type { AgentConfigPermission } from './agentConfigPermission'

export interface AgentConfig {
  model?: string
  temperature?: number
  top_p?: number
  prompt?: string
  tools?: AgentConfigTools
  disable?: boolean
  /** Description of when to use the agent */
  description?: string
  mode?: AgentConfigMode
  permission?: AgentConfigPermission
  [key: string]: unknown
}
