/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

/**
 * Log level
 */
export type AppLogBodyLevel =
  (typeof AppLogBodyLevel)[keyof typeof AppLogBodyLevel]

 
export const AppLogBodyLevel = {
  debug: 'debug',
  info: 'info',
  error: 'error',
  warn: 'warn',
} as const
