/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

/**
 * Additional metadata for the log entry
 */
export type AppLogBodyExtra = { [key: string]: unknown }
