/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { AppLogBodyLevel } from './appLogBodyLevel'
import type { AppLogBodyExtra } from './appLogBodyExtra'

export type AppLogBody = {
  /** Service name for the log entry */
  service: string
  /** Log level */
  level: AppLogBodyLevel
  /** Log message */
  message: string
  /** Additional metadata for the log entry */
  extra?: AppLogBodyExtra
}
