/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { AssistantMessageTime } from './assistantMessageTime'
import type { AssistantMessageError } from './assistantMessageError'
import type { AssistantMessagePath } from './assistantMessagePath'
import type { AssistantMessageTokens } from './assistantMessageTokens'

export interface AssistantMessage {
  id: string
  sessionID: string
  role: 'assistant'
  time: AssistantMessageTime
  error?: AssistantMessageError
  system: string[]
  parentID: string
  modelID: string
  providerID: string
  mode: string
  path: AssistantMessagePath
  summary?: boolean
  cost: number
  tokens: AssistantMessageTokens
}
