/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { OAuth } from './oAuth'
import type { ApiAuth } from './apiAuth'
import type { WellKnownAuth } from './wellKnownAuth'

export type Auth = OAuth | ApiAuth | WellKnownAuth
