/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { BadRequestErrorData } from './badRequestErrorData'
import type { BadRequestErrorErrorsItem } from './badRequestErrorErrorsItem'

export interface BadRequestError {
  data: BadRequestErrorData
  errors: BadRequestErrorErrorsItem[]
  success: false
}
