/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

/**
 * Control sharing behavior:'manual' allows manual sharing via commands, 'auto' enables automatic sharing, 'disabled' disables all sharing
 */
export type ConfigShare = (typeof ConfigShare)[keyof typeof ConfigShare]

 
export const ConfigShare = {
  manual: 'manual',
  auto: 'auto',
  disabled: 'disabled',
} as const
