/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export type ConfigProviderModelsModalitiesOutputItem =
  (typeof ConfigProviderModelsModalitiesOutputItem)[keyof typeof ConfigProviderModelsModalitiesOutputItem]

 
export const ConfigProviderModelsModalitiesOutputItem = {
  text: 'text',
  audio: 'audio',
  image: 'image',
  video: 'video',
  pdf: 'pdf',
} as const
