/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ConfigFormatterEnvironment } from './configFormatterEnvironment'

export type ConfigFormatter = {
  [key: string]: {
    disabled?: boolean
    command?: Array<string>
    environment?: ConfigFormatterEnvironment
    extensions?: Array<string>
  }
}
