/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ConfigLspAnyOfTwoEnv } from './configLspAnyOfTwoEnv'
import type { ConfigLspAnyOfTwoInitialization } from './configLspAnyOfTwoInitialization'

export type ConfigLspAnyOfTwo = {
  command: Array<string>
  extensions?: Array<string>
  disabled?: boolean
  env?: ConfigLspAnyOfTwoEnv
  initialization?: ConfigLspAnyOfTwoInitialization
}
