/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ConfigExperimentalHook } from './configExperimentalHook'

export type ConfigExperimental = {
  hook?: ConfigExperimentalHook
  /** Number of retries for chat completions on failure */
  chatMaxRetries?: number
  disable_paste_summary?: boolean
}
