/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ConfigProviderModels } from './configProviderModels'
import type { ConfigProviderOptions } from './configProviderOptions'

/**
 * Custom provider configurations and model overrides
 */
export type ConfigProvider = {
  [key: string]: {
    api?: string
    name?: string
    env?: Array<string>
    id?: string
    npm?: string
    models?: ConfigProviderModels
    options?: ConfigProviderOptions
  }
}
