/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ConfigProviderOptionsTimeout } from './configProviderOptionsTimeout'

export type ConfigProviderOptions = {
  apiKey?: string
  baseURL?: string
  /** Timeout in milliseconds for requests to this provider. Default is 300000 (5 minutes). Set to false to disable timeout. */
  timeout?: ConfigProviderOptionsTimeout
  [key: string]: unknown
}
