/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { Provider } from './provider'
import type { ConfigProviders200Default } from './configProviders200Default'

export type ConfigProviders200 = {
  providers: Provider[]
  default: ConfigProviders200Default
}
