/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { McpLocalConfig } from './mcpLocalConfig'
import type { McpRemoteConfig } from './mcpRemoteConfig'

/**
 * MCP (Model Context Protocol) server configurations
 */
export type ConfigMcp = { [key: string]: McpLocalConfig | McpRemoteConfig }
