/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ConfigPermissionEdit } from './configPermissionEdit'
import type { ConfigPermissionBash } from './configPermissionBash'
import type { ConfigPermissionWebfetch } from './configPermissionWebfetch'

export type ConfigPermission = {
  edit?: ConfigPermissionEdit
  bash?: ConfigPermissionBash
  webfetch?: ConfigPermissionWebfetch
}
