/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ConfigProviderModelsCost } from './configProviderModelsCost'
import type { ConfigProviderModelsLimit } from './configProviderModelsLimit'
import type { ConfigProviderModelsModalities } from './configProviderModelsModalities'
import type { ConfigProviderModelsStatus } from './configProviderModelsStatus'
import type { ConfigProviderModelsOptions } from './configProviderModelsOptions'
import type { ConfigProviderModelsProvider } from './configProviderModelsProvider'

export type ConfigProviderModels = {
  [key: string]: {
    id?: string
    name?: string
    release_date?: string
    attachment?: boolean
    reasoning?: boolean
    temperature?: boolean
    tool_call?: boolean
    cost?: ConfigProviderModelsCost
    limit?: ConfigProviderModelsLimit
    modalities?: ConfigProviderModelsModalities
    experimental?: boolean
    status?: ConfigProviderModelsStatus
    options?: ConfigProviderModelsOptions
    provider?: ConfigProviderModelsProvider
  }
}
