/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export type ConfigProviderModelsStatus =
  (typeof ConfigProviderModelsStatus)[keyof typeof ConfigProviderModelsStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConfigProviderModelsStatus = {
  alpha: 'alpha',
  beta: 'beta',
} as const
