/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ConfigExperimentalHookFileEdited } from './configExperimentalHookFileEdited'
import type { ConfigExperimentalHookSessionCompletedItem } from './configExperimentalHookSessionCompletedItem'

export type ConfigExperimentalHook = {
  file_edited?: ConfigExperimentalHookFileEdited
  session_completed?: ConfigExperimentalHookSessionCompletedItem[]
}
