/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ConfigProviderModelsModalitiesInputItem } from './configProviderModelsModalitiesInputItem'
import type { ConfigProviderModelsModalitiesOutputItem } from './configProviderModelsModalitiesOutputItem'

export type ConfigProviderModelsModalities = {
  input: ConfigProviderModelsModalitiesInputItem[]
  output: ConfigProviderModelsModalitiesOutputItem[]
}
