/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { AgentConfig } from './agentConfig'

/**
 * Agent configuration, see https://opencode.ai/docs/agent
 */
export type ConfigAgent = {
  plan?: AgentConfig
  build?: AgentConfig
  general?: AgentConfig
  [key: string]: AgentConfig
}
