/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { KeybindsConfig } from './keybindsConfig'
import type { ConfigTui } from './configTui'
import type { ConfigCommand } from './configCommand'
import type { ConfigWatcher } from './configWatcher'
import type { ConfigShare } from './configShare'
import type { ConfigMode } from './configMode'
import type { ConfigAgent } from './configAgent'
import type { ConfigProvider } from './configProvider'
import type { ConfigMcp } from './configMcp'
import type { ConfigFormatter } from './configFormatter'
import type { ConfigLsp } from './configLsp'
import type { LayoutConfig } from './layoutConfig'
import type { ConfigPermission } from './configPermission'
import type { ConfigTools } from './configTools'
import type { ConfigExperimental } from './configExperimental'

export interface Config {
  /** JSON schema reference for configuration validation */
  $schema?: string
  /** Theme name to use for the interface */
  theme?: string
  keybinds?: KeybindsConfig
  /** TUI specific settings */
  tui?: ConfigTui
  /** Command configuration, see https://opencode.ai/docs/commands */
  command?: ConfigCommand
  watcher?: ConfigWatcher
  plugin?: Array<string>
  snapshot?: boolean
  /** Control sharing behavior:'manual' allows manual sharing via commands, 'auto' enables automatic sharing, 'disabled' disables all sharing */
  share?: ConfigShare
  /** @deprecated Use 'share' field instead. Share newly created sessions automatically */
  autoshare?: boolean
  /** Automatically update to the latest version */
  autoupdate?: boolean
  /** Disable providers that are loaded automatically */
  disabled_providers?: Array<string>
  /** Model to use in the format of provider/model, eg anthropic/claude-2 */
  model?: string
  /** Small model to use for tasks like title generation in the format of provider/model */
  small_model?: string
  /** Custom username to display in conversations instead of system username */
  username?: string
  /** @deprecated Use `agent` field instead. */
  mode?: ConfigMode
  /** Agent configuration, see https://opencode.ai/docs/agent */
  agent?: ConfigAgent
  /** Custom provider configurations and model overrides */
  provider?: ConfigProvider
  /** MCP (Model Context Protocol) server configurations */
  mcp?: ConfigMcp
  formatter?: ConfigFormatter
  lsp?: ConfigLsp
  /** Additional instruction files or patterns to include */
  instructions?: Array<string>
  layout?: LayoutConfig
  permission?: ConfigPermission
  tools?: ConfigTools
  experimental?: ConfigExperimental
}
