/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { AgentConfig } from './agentConfig'

/**
 * @deprecated Use `agent` field instead.
 */
export type ConfigMode = {
  build?: AgentConfig
  plan?: AgentConfig
  [key: string]: AgentConfig
}
