/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

/**
 * Command configuration, see https://opencode.ai/docs/commands
 */
export type ConfigCommand = {
  [key: string]: {
    template: string
    description?: string
    agent?: string
    model?: string
    subtask?: boolean
  }
}
