/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ConfigLspAnyOf } from './configLspAnyOf'
import type { ConfigLspAnyOfTwo } from './configLspAnyOfTwo'

export type ConfigLsp = { [key: string]: ConfigLspAnyOf | ConfigLspAnyOfTwo }
