/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

/**
 * TUI specific settings
 */
export type ConfigTui = {
  /**
   * TUI scroll speed
   * @minimum 1
   */
  scroll_speed?: number
}
