/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export type EventCommandExecutedProperties = {
  name: string
  /** @pattern ^ses.* */
  sessionID: string
  arguments: string
  /** @pattern ^msg.* */
  messageID: string
}
