/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { EventInstallationUpdated } from './eventInstallationUpdated'
import type { EventLspClientDiagnostics } from './eventLspClientDiagnostics'
import type { EventMessageUpdated } from './eventMessageUpdated'
import type { EventMessageRemoved } from './eventMessageRemoved'
import type { EventMessagePartUpdated } from './eventMessagePartUpdated'
import type { EventMessagePartRemoved } from './eventMessagePartRemoved'
import type { EventSessionCompacted } from './eventSessionCompacted'
import type { EventPermissionUpdated } from './eventPermissionUpdated'
import type { EventPermissionReplied } from './eventPermissionReplied'
import type { EventFileEdited } from './eventFileEdited'
import type { EventFileWatcherUpdated } from './eventFileWatcherUpdated'
import type { EventTodoUpdated } from './eventTodoUpdated'
import type { EventSessionIdle } from './eventSessionIdle'
import type { EventSessionUpdated } from './eventSessionUpdated'
import type { EventSessionDeleted } from './eventSessionDeleted'
import type { EventSessionError } from './eventSessionError'
import type { EventServerConnected } from './eventServerConnected'
import type { EventIdeInstalled } from './eventIdeInstalled'

export type Event =
  | EventInstallationUpdated
  | EventLspClientDiagnostics
  | EventMessageUpdated
  | EventMessageRemoved
  | EventMessagePartUpdated
  | EventMessagePartRemoved
  | EventSessionCompacted
  | EventPermissionUpdated
  | EventPermissionReplied
  | EventFileEdited
  | EventFileWatcherUpdated
  | EventTodoUpdated
  | EventSessionIdle
  | EventSessionUpdated
  | EventSessionDeleted
  | EventSessionError
  | EventServerConnected
  | EventIdeInstalled
