/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { EventPermissionRepliedProperties } from './eventPermissionRepliedProperties'

export interface EventPermissionReplied {
  type: 'permission.replied'
  properties: EventPermissionRepliedProperties
}
