/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { EventSessionCompactedProperties } from './eventSessionCompactedProperties'

export interface EventSessionCompacted {
  type: 'session.compacted'
  properties: EventSessionCompactedProperties
}
