/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export type EventTuiCommandExecutePropertiesCommand =
  | 'session.list'
  | 'session.new'
  | 'session.share'
  | 'session.interrupt'
  | 'session.compact'
  | 'session.page.up'
  | 'session.page.down'
  | 'session.half.page.up'
  | 'session.half.page.down'
  | 'session.first'
  | 'session.last'
  | 'prompt.clear'
  | 'prompt.submit'
  | 'agent.cycle'
  | string
