/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { Part } from './part'

export type EventMessagePartUpdatedProperties = {
  part: Part
  delta?: string
}
