/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { EventTuiToastShowProperties } from './eventTuiToastShowProperties'

export interface EventTuiToastShow {
  type: 'tui.toast.show'
  properties: EventTuiToastShowProperties
}
