/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { EventFileWatcherUpdatedProperties } from './eventFileWatcherUpdatedProperties'

export interface EventFileWatcherUpdated {
  type: 'file.watcher.updated'
  properties: EventFileWatcherUpdatedProperties
}
