/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { EventMessagePartRemovedProperties } from './eventMessagePartRemovedProperties'

export interface EventMessagePartRemoved {
  type: 'message.part.removed'
  properties: EventMessagePartRemovedProperties
}
