/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { EventCommandExecutedProperties } from './eventCommandExecutedProperties'

export interface EventCommandExecuted {
  type: 'command.executed'
  properties: EventCommandExecutedProperties
}
