/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export type EventTuiToastShowPropertiesVariant =
  (typeof EventTuiToastShowPropertiesVariant)[keyof typeof EventTuiToastShowPropertiesVariant]

 
export const EventTuiToastShowPropertiesVariant = {
  info: 'info',
  success: 'success',
  warning: 'warning',
  error: 'error',
} as const
