/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ProviderAuthError } from './providerAuthError'
import type { UnknownError } from './unknownError'
import type { MessageOutputLengthError } from './messageOutputLengthError'
import type { MessageAbortedError } from './messageAbortedError'

export type EventSessionErrorPropertiesError =
  | ProviderAuthError
  | UnknownError
  | MessageOutputLengthError
  | MessageAbortedError
