/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { FileStatus } from './fileStatus'

export interface File {
  path: string
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  added: number
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  removed: number
  status: FileStatus
}
