/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export type FileNodeType = (typeof FileNodeType)[keyof typeof FileNodeType]

 
export const FileNodeType = {
  file: 'file',
  directory: 'directory',
} as const
