/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { FileContentPatchHunksItem } from './fileContentPatchHunksItem'

export type FileContentPatch = {
  oldFileName: string
  newFileName: string
  oldHeader?: string
  newHeader?: string
  hunks: Array<FileContentPatchHunksItem>
  index?: string
}
