/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export interface FilePartSourceText {
  value: string
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  start: number
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  end: number
}
