/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { FilePartSourceText } from './filePartSourceText'

export interface FileSource {
  text: FilePartSourceText
  type: 'file'
  path: string
}
