/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { FileContentPatch } from './fileContentPatch'

export interface FileContent {
  type: 'text'
  content: string
  diff?: string
  patch?: FileContentPatch
  encoding?: 'base64'
  mimeType?: string
}
