/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { FindText200ItemPath } from './findText200ItemPath'
import type { FindText200ItemLines } from './findText200ItemLines'
import type { FindText200ItemSubmatchesItem } from './findText200ItemSubmatchesItem'

export type FindText200Item = {
  path: FindText200ItemPath
  lines: FindText200ItemLines
  line_number: number
  absolute_offset: number
  submatches: FindText200ItemSubmatchesItem[]
}
