/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { FindText200ItemSubmatchesItemMatch } from './findText200ItemSubmatchesItemMatch'

export type FindText200ItemSubmatchesItem = {
  match: FindText200ItemSubmatchesItemMatch
  start: number
  end: number
}
