/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

/**
 * Custom keybind configurations
 */
export interface KeybindsConfig {
  /** Leader key for keybind combinations */
  leader?: string
  /** Exit the application */
  app_exit?: string
  /** Open external editor */
  editor_open?: string
  /** List available themes */
  theme_list?: string
  /** Toggle sidebar */
  sidebar_toggle?: string
  /** View status */
  status_view?: string
  /** Export session to editor */
  session_export?: string
  /** Create a new session */
  session_new?: string
  /** List all sessions */
  session_list?: string
  /** Show session timeline */
  session_timeline?: string
  /** Share current session */
  session_share?: string
  /** Unshare current session */
  session_unshare?: string
  /** Interrupt current session */
  session_interrupt?: string
  /** Compact the session */
  session_compact?: string
  /** Scroll messages up by one page */
  messages_page_up?: string
  /** Scroll messages down by one page */
  messages_page_down?: string
  /** Scroll messages up by half page */
  messages_half_page_up?: string
  /** Scroll messages down by half page */
  messages_half_page_down?: string
  /** Navigate to first message */
  messages_first?: string
  /** Navigate to last message */
  messages_last?: string
  /** Copy message */
  messages_copy?: string
  /** Undo message */
  messages_undo?: string
  /** Redo message */
  messages_redo?: string
  /** Toggle code block concealment in messages */
  messages_toggle_conceal?: string
  /** List available models */
  model_list?: string
  /** Next recently used model */
  model_cycle_recent?: string
  /** Previous recently used model */
  model_cycle_recent_reverse?: string
  /** List available commands */
  command_list?: string
  /** List agents */
  agent_list?: string
  /** Next agent */
  agent_cycle?: string
  /** Previous agent */
  agent_cycle_reverse?: string
  /** Clear input field */
  input_clear?: string
  /** Forward delete */
  input_forward_delete?: string
  /** Paste from clipboard */
  input_paste?: string
  /** Submit input */
  input_submit?: string
  /** Insert newline in input */
  input_newline?: string
  /** Previous history item */
  history_previous?: string
  /** Next history item */
  history_next?: string
  /** Next child session */
  session_child_cycle?: string
  /** Previous child session */
  session_child_cycle_reverse?: string
}
