/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

/**
 * @deprecated Always uses stretch layout.
 */
export type LayoutConfig = (typeof LayoutConfig)[keyof typeof LayoutConfig]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LayoutConfig = {
  auto: 'auto',
  stretch: 'stretch',
} as const
