/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { LSPStatusStatus } from './lSPStatusStatus'

export interface LSPStatus {
  id: string
  name: string
  root: string
  status: LSPStatusStatus
}
