/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { McpLocalConfigEnvironment } from './mcpLocalConfigEnvironment'

export interface McpLocalConfig {
  /** Type of MCP server connection */
  type: 'local'
  /** Command and arguments to run the MCP server */
  command: Array<string>
  /** Environment variables to set when running the MCP server */
  environment?: McpLocalConfigEnvironment
  /** Enable or disable the MCP server on startup */
  enabled?: boolean
  /**
   * Timeout in ms for fetching tools from the MCP server. Defaults to 5000 (5 seconds) if not specified.
   * @maximum 9007199254740991
   */
  timeout?: number
}
