/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

/**
 * Environment variables to set when running the MCP server
 */
export type McpLocalConfigEnvironment = { [key: string]: string }
