/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { McpLocalConfigEnvironment } from './mcpLocalConfigEnvironment'

export interface McpLocalConfig {
  /** Type of MCP server connection */
  type: 'local'
  /** Command and arguments to run the MCP server */
  command: string[]
  /** Environment variables to set when running the MCP server */
  environment?: McpLocalConfigEnvironment
  /** Enable or disable the MCP server on startup */
  enabled?: boolean
}
