/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

/**
 * Headers to send with the request
 */
export type McpRemoteConfigHeaders = { [key: string]: string }
