/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { McpRemoteConfigHeaders } from './mcpRemoteConfigHeaders'

export interface McpRemoteConfig {
  /** Type of MCP server connection */
  type: 'remote'
  /** URL of the remote MCP server */
  url: string
  /** Enable or disable the MCP server on startup */
  enabled?: boolean
  /** Headers to send with the request */
  headers?: McpRemoteConfigHeaders
}
