/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { MCPStatusConnected } from './mCPStatusConnected'
import type { MCPStatusDisabled } from './mCPStatusDisabled'
import type { MCPStatusFailed } from './mCPStatusFailed'

export type MCPStatus = MCPStatusConnected | MCPStatusDisabled | MCPStatusFailed
