/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { MessageOutputLengthErrorData } from './messageOutputLengthErrorData'

export interface MessageOutputLengthError {
  name: 'MessageOutputLengthError'
  data: MessageOutputLengthErrorData
}
