/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export type ModelModalitiesOutputItem =
  (typeof ModelModalitiesOutputItem)[keyof typeof ModelModalitiesOutputItem]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelModalitiesOutputItem = {
  text: 'text',
  audio: 'audio',
  image: 'image',
  video: 'video',
  pdf: 'pdf',
} as const
