/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ModelModalitiesInputItem } from './modelModalitiesInputItem'
import type { ModelModalitiesOutputItem } from './modelModalitiesOutputItem'

export type ModelModalities = {
  input: ModelModalitiesInputItem[]
  output: ModelModalitiesOutputItem[]
}
