/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ModelCost } from './modelCost'
import type { ModelLimit } from './modelLimit'
import type { ModelModalities } from './modelModalities'
import type { ModelStatus } from './modelStatus'
import type { ModelOptions } from './modelOptions'
import type { ModelProvider } from './modelProvider'

export interface Model {
  id: string
  name: string
  release_date: string
  attachment: boolean
  reasoning: boolean
  temperature: boolean
  tool_call: boolean
  cost: ModelCost
  limit: ModelLimit
  modalities?: ModelModalities
  experimental?: boolean
  status?: ModelStatus
  options: ModelOptions
  provider?: ModelProvider
}
