/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export type ModelModalitiesInputItem =
  (typeof ModelModalitiesInputItem)[keyof typeof ModelModalitiesInputItem]

 
export const ModelModalitiesInputItem = {
  text: 'text',
  audio: 'audio',
  image: 'image',
  video: 'video',
  pdf: 'pdf',
} as const
