/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { TextPart } from './textPart'
import type { ReasoningPart } from './reasoningPart'
import type { FilePart } from './filePart'
import type { ToolPart } from './toolPart'
import type { StepStartPart } from './stepStartPart'
import type { StepFinishPart } from './stepFinishPart'
import type { SnapshotPart } from './snapshotPart'
import type { PatchPart } from './patchPart'
import type { AgentPart } from './agentPart'
import type { RetryPart } from './retryPart'

export type Part =
  | TextPart
  | ReasoningPart
  | FilePart
  | ToolPart
  | StepStartPart
  | StepFinishPart
  | SnapshotPart
  | PatchPart
  | AgentPart
  | RetryPart
