/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export interface PatchPart {
  id: string
  sessionID: string
  messageID: string
  type: 'patch'
  hash: string
  files: string[]
}
