/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { PermissionPattern } from './permissionPattern'
import type { PermissionMetadata } from './permissionMetadata'
import type { PermissionTime } from './permissionTime'

export interface Permission {
  id: string
  type: string
  pattern?: PermissionPattern
  sessionID: string
  messageID: string
  callID?: string
  title: string
  metadata: PermissionMetadata
  time: PermissionTime
}
