/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export type PostSessionIdPermissionsPermissionIDBodyResponse =
  (typeof PostSessionIdPermissionsPermissionIDBodyResponse)[keyof typeof PostSessionIdPermissionsPermissionIDBodyResponse]

 
export const PostSessionIdPermissionsPermissionIDBodyResponse = {
  once: 'once',
  always: 'always',
  reject: 'reject',
} as const
