/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ProviderModels } from './providerModels'

export interface Provider {
  api?: string
  name: string
  env: Array<string>
  id: string
  npm?: string
  models: ProviderModels
}
