/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ReasoningPartMetadata } from './reasoningPartMetadata'
import type { ReasoningPartTime } from './reasoningPartTime'

export interface ReasoningPart {
  id: string
  sessionID: string
  messageID: string
  type: 'reasoning'
  text: string
  metadata?: ReasoningPartMetadata
  time: ReasoningPartTime
}
