/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { APIError } from './aPIError'
import type { RetryPartTime } from './retryPartTime'

export interface RetryPart {
  id: string
  sessionID: string
  messageID: string
  type: 'retry'
  attempt: number
  error: APIError
  time: RetryPartTime
}
