/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { SessionPromptBodyModel } from './sessionPromptBodyModel'
import type { SessionPromptBodyTools } from './sessionPromptBodyTools'
import type { SessionPromptBodyPartsItem } from './sessionPromptBodyPartsItem'

export type SessionPromptBody = {
  /** @pattern ^msg.* */
  messageID?: string
  model?: SessionPromptBodyModel
  agent?: string
  noReply?: boolean
  system?: string
  tools?: SessionPromptBodyTools
  parts: Array<SessionPromptBodyPartsItem>
}
