/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { AssistantMessage } from './assistantMessage'
import type { Part } from './part'

export type SessionPrompt200 = {
  info: AssistantMessage
  parts: Array<Part>
}
