/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { SessionShare } from './sessionShare'
import type { SessionTime } from './sessionTime'
import type { SessionRevert } from './sessionRevert'

export interface Session {
  /** @pattern ^ses.* */
  id: string
  projectID: string
  directory: string
  /** @pattern ^ses.* */
  parentID?: string
  share?: SessionShare
  title: string
  version: string
  time: SessionTime
  revert?: SessionRevert
}
