/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export type SessionRevertBody = {
  /** @pattern ^msg.* */
  messageID: string
  /** @pattern ^prt.* */
  partID?: string
}
