/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { TextPartInput } from './textPartInput'
import type { FilePartInput } from './filePartInput'
import type { AgentPartInput } from './agentPartInput'

export type SessionPromptBodyPartsItem =
  | TextPartInput
  | FilePartInput
  | AgentPartInput
