/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { StepFinishPartTokensCache } from './stepFinishPartTokensCache'

export type StepFinishPartTokens = {
  input: number
  output: number
  reasoning: number
  cache: StepFinishPartTokensCache
}
