/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export interface StepStartPart {
  id: string
  sessionID: string
  messageID: string
  type: 'step-start'
}
