/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { StepFinishPartTokens } from './stepFinishPartTokens'

export interface StepFinishPart {
  id: string
  sessionID: string
  messageID: string
  type: 'step-finish'
  cost: number
  tokens: StepFinishPartTokens
}
