/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { FilePartSourceText } from './filePartSourceText'
import type { Range } from './range'

export interface SymbolSource {
  text: FilePartSourceText
  type: 'symbol'
  path: string
  range: Range
  name: string
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  kind: number
}
