/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { TextPartInputTime } from './textPartInputTime'
import type { TextPartInputMetadata } from './textPartInputMetadata'

export interface TextPartInput {
  id?: string
  type: 'text'
  text: string
  synthetic?: boolean
  time?: TextPartInputTime
  metadata?: TextPartInputMetadata
}
