/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export interface Todo {
  /** Brief description of the task */
  content: string
  /** Current status of the task: pending, in_progress, completed, cancelled */
  status: string
  /** Priority level of the task: high, medium, low */
  priority: string
  /** Unique identifier for the todo item */
  id: string
}
