/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ToolStateCompletedInput } from './toolStateCompletedInput'
import type { ToolStateCompletedMetadata } from './toolStateCompletedMetadata'
import type { ToolStateCompletedTime } from './toolStateCompletedTime'
import type { FilePart } from './filePart'

export interface ToolStateCompleted {
  status: 'completed'
  input: ToolStateCompletedInput
  output: string
  title: string
  metadata: ToolStateCompletedMetadata
  time: ToolStateCompletedTime
  attachments?: FilePart[]
}
