/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ToolStatePending } from './toolStatePending'
import type { ToolStateRunning } from './toolStateRunning'
import type { ToolStateCompleted } from './toolStateCompleted'
import type { ToolStateError } from './toolStateError'

export type ToolState =
  | ToolStatePending
  | ToolStateRunning
  | ToolStateCompleted
  | ToolStateError
