/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ToolStateRunningMetadata } from './toolStateRunningMetadata'
import type { ToolStateRunningTime } from './toolStateRunningTime'

export interface ToolStateRunning {
  status: 'running'
  input: unknown
  title?: string
  metadata?: ToolStateRunningMetadata
  time: ToolStateRunningTime
}
