/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { ToolStateErrorInput } from './toolStateErrorInput'
import type { ToolStateErrorMetadata } from './toolStateErrorMetadata'
import type { ToolStateErrorTime } from './toolStateErrorTime'

export interface ToolStateError {
  status: 'error'
  input: ToolStateErrorInput
  error: string
  metadata?: ToolStateErrorMetadata
  time: ToolStateErrorTime
}
