/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { EventTuiPromptAppend } from './eventTuiPromptAppend'
import type { EventTuiCommandExecute } from './eventTuiCommandExecute'
import type { EventTuiToastShow } from './eventTuiToastShow'

export type TuiPublishBody =
  | EventTuiPromptAppend
  | EventTuiCommandExecute
  | EventTuiToastShow
