/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export type TuiShowToastBodyVariant =
  (typeof TuiShowToastBodyVariant)[keyof typeof TuiShowToastBodyVariant]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TuiShowToastBodyVariant = {
  info: 'info',
  success: 'success',
  warning: 'warning',
  error: 'error',
} as const
