/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */
import type { FileDiff } from './fileDiff'

export type UserMessageSummary = {
  title?: string
  body?: string
  diffs: FileDiff[]
}
