/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * opencode
 * opencode api
 * OpenAPI spec version: 0.0.3
 */

export interface WellKnownAuth {
  type: 'wellknown'
  key: string
  token: string
}
