/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServersRouteRouteImport } from './routes/servers/route'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as ServersServerIdRouteImport } from './routes/servers/$serverId'
import { Route as ServersServerIdSessionsRouteImport } from './routes/servers/$serverId.sessions'
import { Route as ServersServerIdChatSessionIdRouteImport } from './routes/servers/$serverId_.chat.$sessionId'

const ServersRouteRoute = ServersRouteRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServersRouteRoute,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => ServersRouteRoute,
} as any)
const ServersServerIdSessionsRoute = ServersServerIdSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ServersServerIdRoute,
} as any)
const ServersServerIdChatSessionIdRoute =
  ServersServerIdChatSessionIdRouteImport.update({
    id: '/$serverId_/chat/$sessionId',
    path: '/$serverId/chat/$sessionId',
    getParentRoute: () => ServersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/servers': typeof ServersRouteRouteWithChildren
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/servers/': typeof ServersIndexRoute
  '/servers/$serverId/sessions': typeof ServersServerIdSessionsRoute
  '/servers/$serverId/chat/$sessionId': typeof ServersServerIdChatSessionIdRoute
}
export interface FileRoutesByTo {
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/servers': typeof ServersIndexRoute
  '/servers/$serverId/sessions': typeof ServersServerIdSessionsRoute
  '/servers/$serverId/chat/$sessionId': typeof ServersServerIdChatSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/servers': typeof ServersRouteRouteWithChildren
  '/servers/$serverId': typeof ServersServerIdRouteWithChildren
  '/servers/': typeof ServersIndexRoute
  '/servers/$serverId/sessions': typeof ServersServerIdSessionsRoute
  '/servers/$serverId_/chat/$sessionId': typeof ServersServerIdChatSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/servers'
    | '/servers/$serverId'
    | '/servers/'
    | '/servers/$serverId/sessions'
    | '/servers/$serverId/chat/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/servers/$serverId'
    | '/servers'
    | '/servers/$serverId/sessions'
    | '/servers/$serverId/chat/$sessionId'
  id:
    | '__root__'
    | '/servers'
    | '/servers/$serverId'
    | '/servers/'
    | '/servers/$serverId/sessions'
    | '/servers/$serverId_/chat/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ServersRouteRoute: typeof ServersRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof ServersRouteRoute
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof ServersRouteRoute
    }
    '/servers/$serverId/sessions': {
      id: '/servers/$serverId/sessions'
      path: '/sessions'
      fullPath: '/servers/$serverId/sessions'
      preLoaderRoute: typeof ServersServerIdSessionsRouteImport
      parentRoute: typeof ServersServerIdRoute
    }
    '/servers/$serverId_/chat/$sessionId': {
      id: '/servers/$serverId_/chat/$sessionId'
      path: '/$serverId/chat/$sessionId'
      fullPath: '/servers/$serverId/chat/$sessionId'
      preLoaderRoute: typeof ServersServerIdChatSessionIdRouteImport
      parentRoute: typeof ServersRouteRoute
    }
  }
}

interface ServersServerIdRouteChildren {
  ServersServerIdSessionsRoute: typeof ServersServerIdSessionsRoute
}

const ServersServerIdRouteChildren: ServersServerIdRouteChildren = {
  ServersServerIdSessionsRoute: ServersServerIdSessionsRoute,
}

const ServersServerIdRouteWithChildren = ServersServerIdRoute._addFileChildren(
  ServersServerIdRouteChildren,
)

interface ServersRouteRouteChildren {
  ServersServerIdRoute: typeof ServersServerIdRouteWithChildren
  ServersIndexRoute: typeof ServersIndexRoute
  ServersServerIdChatSessionIdRoute: typeof ServersServerIdChatSessionIdRoute
}

const ServersRouteRouteChildren: ServersRouteRouteChildren = {
  ServersServerIdRoute: ServersServerIdRouteWithChildren,
  ServersIndexRoute: ServersIndexRoute,
  ServersServerIdChatSessionIdRoute: ServersServerIdChatSessionIdRoute,
}

const ServersRouteRouteWithChildren = ServersRouteRoute._addFileChildren(
  ServersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ServersRouteRoute: ServersRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
