/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServersRouteRouteImport } from './routes/servers/route'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as ServersServerIdIndexRouteImport } from './routes/servers/$serverId/index'
import { Route as ServersServerIdSessionsRouteImport } from './routes/servers/$serverId/sessions'
import { Route as ServersServerIdChatNewRouteImport } from './routes/servers/$serverId/chat/new'
import { Route as ServersServerIdChatSessionIdRouteImport } from './routes/servers/$serverId/chat/$sessionId'

const ServersRouteRoute = ServersRouteRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServersRouteRoute,
} as any)
const ServersServerIdIndexRoute = ServersServerIdIndexRouteImport.update({
  id: '/$serverId/',
  path: '/$serverId/',
  getParentRoute: () => ServersRouteRoute,
} as any)
const ServersServerIdSessionsRoute = ServersServerIdSessionsRouteImport.update({
  id: '/$serverId/sessions',
  path: '/$serverId/sessions',
  getParentRoute: () => ServersRouteRoute,
} as any)
const ServersServerIdChatNewRoute = ServersServerIdChatNewRouteImport.update({
  id: '/$serverId/chat/new',
  path: '/$serverId/chat/new',
  getParentRoute: () => ServersRouteRoute,
} as any)
const ServersServerIdChatSessionIdRoute =
  ServersServerIdChatSessionIdRouteImport.update({
    id: '/$serverId/chat/$sessionId',
    path: '/$serverId/chat/$sessionId',
    getParentRoute: () => ServersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/servers': typeof ServersRouteRouteWithChildren
  '/servers/': typeof ServersIndexRoute
  '/servers/$serverId/sessions': typeof ServersServerIdSessionsRoute
  '/servers/$serverId': typeof ServersServerIdIndexRoute
  '/servers/$serverId/chat/$sessionId': typeof ServersServerIdChatSessionIdRoute
  '/servers/$serverId/chat/new': typeof ServersServerIdChatNewRoute
}
export interface FileRoutesByTo {
  '/servers': typeof ServersIndexRoute
  '/servers/$serverId/sessions': typeof ServersServerIdSessionsRoute
  '/servers/$serverId': typeof ServersServerIdIndexRoute
  '/servers/$serverId/chat/$sessionId': typeof ServersServerIdChatSessionIdRoute
  '/servers/$serverId/chat/new': typeof ServersServerIdChatNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/servers': typeof ServersRouteRouteWithChildren
  '/servers/': typeof ServersIndexRoute
  '/servers/$serverId/sessions': typeof ServersServerIdSessionsRoute
  '/servers/$serverId/': typeof ServersServerIdIndexRoute
  '/servers/$serverId/chat/$sessionId': typeof ServersServerIdChatSessionIdRoute
  '/servers/$serverId/chat/new': typeof ServersServerIdChatNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/servers'
    | '/servers/'
    | '/servers/$serverId/sessions'
    | '/servers/$serverId'
    | '/servers/$serverId/chat/$sessionId'
    | '/servers/$serverId/chat/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/servers'
    | '/servers/$serverId/sessions'
    | '/servers/$serverId'
    | '/servers/$serverId/chat/$sessionId'
    | '/servers/$serverId/chat/new'
  id:
    | '__root__'
    | '/servers'
    | '/servers/'
    | '/servers/$serverId/sessions'
    | '/servers/$serverId/'
    | '/servers/$serverId/chat/$sessionId'
    | '/servers/$serverId/chat/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ServersRouteRoute: typeof ServersRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof ServersRouteRoute
    }
    '/servers/$serverId/': {
      id: '/servers/$serverId/'
      path: '/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdIndexRouteImport
      parentRoute: typeof ServersRouteRoute
    }
    '/servers/$serverId/sessions': {
      id: '/servers/$serverId/sessions'
      path: '/$serverId/sessions'
      fullPath: '/servers/$serverId/sessions'
      preLoaderRoute: typeof ServersServerIdSessionsRouteImport
      parentRoute: typeof ServersRouteRoute
    }
    '/servers/$serverId/chat/new': {
      id: '/servers/$serverId/chat/new'
      path: '/$serverId/chat/new'
      fullPath: '/servers/$serverId/chat/new'
      preLoaderRoute: typeof ServersServerIdChatNewRouteImport
      parentRoute: typeof ServersRouteRoute
    }
    '/servers/$serverId/chat/$sessionId': {
      id: '/servers/$serverId/chat/$sessionId'
      path: '/$serverId/chat/$sessionId'
      fullPath: '/servers/$serverId/chat/$sessionId'
      preLoaderRoute: typeof ServersServerIdChatSessionIdRouteImport
      parentRoute: typeof ServersRouteRoute
    }
  }
}

interface ServersRouteRouteChildren {
  ServersIndexRoute: typeof ServersIndexRoute
  ServersServerIdSessionsRoute: typeof ServersServerIdSessionsRoute
  ServersServerIdIndexRoute: typeof ServersServerIdIndexRoute
  ServersServerIdChatSessionIdRoute: typeof ServersServerIdChatSessionIdRoute
  ServersServerIdChatNewRoute: typeof ServersServerIdChatNewRoute
}

const ServersRouteRouteChildren: ServersRouteRouteChildren = {
  ServersIndexRoute: ServersIndexRoute,
  ServersServerIdSessionsRoute: ServersServerIdSessionsRoute,
  ServersServerIdIndexRoute: ServersServerIdIndexRoute,
  ServersServerIdChatSessionIdRoute: ServersServerIdChatSessionIdRoute,
  ServersServerIdChatNewRoute: ServersServerIdChatNewRoute,
}

const ServersRouteRouteWithChildren = ServersRouteRoute._addFileChildren(
  ServersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ServersRouteRoute: ServersRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
